// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.edu.signalAlgorithm.proto;

public final class HelloProto {
  private HelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:helloworld.HelloRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code helloworld.HelloRequest}
   */
  public static final class HelloRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:helloworld.HelloRequest)
      HelloRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloRequest.newBuilder() to construct.
    private HelloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloRequest() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HelloRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_HelloRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_HelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.edu.signalAlgorithm.proto.HelloProto.HelloRequest.class, com.edu.signalAlgorithm.proto.HelloProto.HelloRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.edu.signalAlgorithm.proto.HelloProto.HelloRequest)) {
        return super.equals(obj);
      }
      com.edu.signalAlgorithm.proto.HelloProto.HelloRequest other = (com.edu.signalAlgorithm.proto.HelloProto.HelloRequest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.edu.signalAlgorithm.proto.HelloProto.HelloRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code helloworld.HelloRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:helloworld.HelloRequest)
        com.edu.signalAlgorithm.proto.HelloProto.HelloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_HelloRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_HelloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.edu.signalAlgorithm.proto.HelloProto.HelloRequest.class, com.edu.signalAlgorithm.proto.HelloProto.HelloRequest.Builder.class);
      }

      // Construct using com.edu.signalAlgorithm.proto.HelloProto.HelloRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_HelloRequest_descriptor;
      }

      @java.lang.Override
      public com.edu.signalAlgorithm.proto.HelloProto.HelloRequest getDefaultInstanceForType() {
        return com.edu.signalAlgorithm.proto.HelloProto.HelloRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.edu.signalAlgorithm.proto.HelloProto.HelloRequest build() {
        com.edu.signalAlgorithm.proto.HelloProto.HelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.edu.signalAlgorithm.proto.HelloProto.HelloRequest buildPartial() {
        com.edu.signalAlgorithm.proto.HelloProto.HelloRequest result = new com.edu.signalAlgorithm.proto.HelloProto.HelloRequest(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.edu.signalAlgorithm.proto.HelloProto.HelloRequest) {
          return mergeFrom((com.edu.signalAlgorithm.proto.HelloProto.HelloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.edu.signalAlgorithm.proto.HelloProto.HelloRequest other) {
        if (other == com.edu.signalAlgorithm.proto.HelloProto.HelloRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.edu.signalAlgorithm.proto.HelloProto.HelloRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.edu.signalAlgorithm.proto.HelloProto.HelloRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:helloworld.HelloRequest)
    }

    // @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
    private static final com.edu.signalAlgorithm.proto.HelloProto.HelloRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.edu.signalAlgorithm.proto.HelloProto.HelloRequest();
    }

    public static com.edu.signalAlgorithm.proto.HelloProto.HelloRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloRequest>
        PARSER = new com.google.protobuf.AbstractParser<HelloRequest>() {
      @java.lang.Override
      public HelloRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.edu.signalAlgorithm.proto.HelloProto.HelloRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HelloReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:helloworld.HelloReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
     */
    java.util.List<com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures> 
        getTdfList();
    /**
     * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
     */
    com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures getTdf(int index);
    /**
     * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
     */
    int getTdfCount();
    /**
     * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
     */
    java.util.List<? extends com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeaturesOrBuilder> 
        getTdfOrBuilderList();
    /**
     * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
     */
    com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeaturesOrBuilder getTdfOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code helloworld.HelloReply}
   */
  public static final class HelloReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:helloworld.HelloReply)
      HelloReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloReply.newBuilder() to construct.
    private HelloReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloReply() {
      message_ = "";
      tdf_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HelloReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tdf_ = new java.util.ArrayList<com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures>();
                mutable_bitField0_ |= 0x00000001;
              }
              tdf_.add(
                  input.readMessage(com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          tdf_ = java.util.Collections.unmodifiableList(tdf_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_HelloReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_HelloReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.edu.signalAlgorithm.proto.HelloProto.HelloReply.class, com.edu.signalAlgorithm.proto.HelloProto.HelloReply.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TDF_FIELD_NUMBER = 2;
    private java.util.List<com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures> tdf_;
    /**
     * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures> getTdfList() {
      return tdf_;
    }
    /**
     * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeaturesOrBuilder> 
        getTdfOrBuilderList() {
      return tdf_;
    }
    /**
     * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
     */
    @java.lang.Override
    public int getTdfCount() {
      return tdf_.size();
    }
    /**
     * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
     */
    @java.lang.Override
    public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures getTdf(int index) {
      return tdf_.get(index);
    }
    /**
     * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
     */
    @java.lang.Override
    public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeaturesOrBuilder getTdfOrBuilder(
        int index) {
      return tdf_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      for (int i = 0; i < tdf_.size(); i++) {
        output.writeMessage(2, tdf_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      for (int i = 0; i < tdf_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, tdf_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.edu.signalAlgorithm.proto.HelloProto.HelloReply)) {
        return super.equals(obj);
      }
      com.edu.signalAlgorithm.proto.HelloProto.HelloReply other = (com.edu.signalAlgorithm.proto.HelloProto.HelloReply) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getTdfList()
          .equals(other.getTdfList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (getTdfCount() > 0) {
        hash = (37 * hash) + TDF_FIELD_NUMBER;
        hash = (53 * hash) + getTdfList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.edu.signalAlgorithm.proto.HelloProto.HelloReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code helloworld.HelloReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:helloworld.HelloReply)
        com.edu.signalAlgorithm.proto.HelloProto.HelloReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_HelloReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_HelloReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.edu.signalAlgorithm.proto.HelloProto.HelloReply.class, com.edu.signalAlgorithm.proto.HelloProto.HelloReply.Builder.class);
      }

      // Construct using com.edu.signalAlgorithm.proto.HelloProto.HelloReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTdfFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = "";

        if (tdfBuilder_ == null) {
          tdf_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tdfBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_HelloReply_descriptor;
      }

      @java.lang.Override
      public com.edu.signalAlgorithm.proto.HelloProto.HelloReply getDefaultInstanceForType() {
        return com.edu.signalAlgorithm.proto.HelloProto.HelloReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.edu.signalAlgorithm.proto.HelloProto.HelloReply build() {
        com.edu.signalAlgorithm.proto.HelloProto.HelloReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.edu.signalAlgorithm.proto.HelloProto.HelloReply buildPartial() {
        com.edu.signalAlgorithm.proto.HelloProto.HelloReply result = new com.edu.signalAlgorithm.proto.HelloProto.HelloReply(this);
        int from_bitField0_ = bitField0_;
        result.message_ = message_;
        if (tdfBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            tdf_ = java.util.Collections.unmodifiableList(tdf_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tdf_ = tdf_;
        } else {
          result.tdf_ = tdfBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.edu.signalAlgorithm.proto.HelloProto.HelloReply) {
          return mergeFrom((com.edu.signalAlgorithm.proto.HelloProto.HelloReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.edu.signalAlgorithm.proto.HelloProto.HelloReply other) {
        if (other == com.edu.signalAlgorithm.proto.HelloProto.HelloReply.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (tdfBuilder_ == null) {
          if (!other.tdf_.isEmpty()) {
            if (tdf_.isEmpty()) {
              tdf_ = other.tdf_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTdfIsMutable();
              tdf_.addAll(other.tdf_);
            }
            onChanged();
          }
        } else {
          if (!other.tdf_.isEmpty()) {
            if (tdfBuilder_.isEmpty()) {
              tdfBuilder_.dispose();
              tdfBuilder_ = null;
              tdf_ = other.tdf_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tdfBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTdfFieldBuilder() : null;
            } else {
              tdfBuilder_.addAllMessages(other.tdf_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.edu.signalAlgorithm.proto.HelloProto.HelloReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.edu.signalAlgorithm.proto.HelloProto.HelloReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures> tdf_ =
        java.util.Collections.emptyList();
      private void ensureTdfIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tdf_ = new java.util.ArrayList<com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures>(tdf_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeaturesOrBuilder> tdfBuilder_;

      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public java.util.List<com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures> getTdfList() {
        if (tdfBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tdf_);
        } else {
          return tdfBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public int getTdfCount() {
        if (tdfBuilder_ == null) {
          return tdf_.size();
        } else {
          return tdfBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures getTdf(int index) {
        if (tdfBuilder_ == null) {
          return tdf_.get(index);
        } else {
          return tdfBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public Builder setTdf(
          int index, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures value) {
        if (tdfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTdfIsMutable();
          tdf_.set(index, value);
          onChanged();
        } else {
          tdfBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public Builder setTdf(
          int index, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder builderForValue) {
        if (tdfBuilder_ == null) {
          ensureTdfIsMutable();
          tdf_.set(index, builderForValue.build());
          onChanged();
        } else {
          tdfBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public Builder addTdf(com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures value) {
        if (tdfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTdfIsMutable();
          tdf_.add(value);
          onChanged();
        } else {
          tdfBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public Builder addTdf(
          int index, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures value) {
        if (tdfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTdfIsMutable();
          tdf_.add(index, value);
          onChanged();
        } else {
          tdfBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public Builder addTdf(
          com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder builderForValue) {
        if (tdfBuilder_ == null) {
          ensureTdfIsMutable();
          tdf_.add(builderForValue.build());
          onChanged();
        } else {
          tdfBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public Builder addTdf(
          int index, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder builderForValue) {
        if (tdfBuilder_ == null) {
          ensureTdfIsMutable();
          tdf_.add(index, builderForValue.build());
          onChanged();
        } else {
          tdfBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public Builder addAllTdf(
          java.lang.Iterable<? extends com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures> values) {
        if (tdfBuilder_ == null) {
          ensureTdfIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tdf_);
          onChanged();
        } else {
          tdfBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public Builder clearTdf() {
        if (tdfBuilder_ == null) {
          tdf_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tdfBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public Builder removeTdf(int index) {
        if (tdfBuilder_ == null) {
          ensureTdfIsMutable();
          tdf_.remove(index);
          onChanged();
        } else {
          tdfBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder getTdfBuilder(
          int index) {
        return getTdfFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeaturesOrBuilder getTdfOrBuilder(
          int index) {
        if (tdfBuilder_ == null) {
          return tdf_.get(index);  } else {
          return tdfBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public java.util.List<? extends com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeaturesOrBuilder> 
           getTdfOrBuilderList() {
        if (tdfBuilder_ != null) {
          return tdfBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tdf_);
        }
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder addTdfBuilder() {
        return getTdfFieldBuilder().addBuilder(
            com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.getDefaultInstance());
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder addTdfBuilder(
          int index) {
        return getTdfFieldBuilder().addBuilder(
            index, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.getDefaultInstance());
      }
      /**
       * <code>repeated .helloworld.TimeDomainFeatures tdf = 2;</code>
       */
      public java.util.List<com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder> 
           getTdfBuilderList() {
        return getTdfFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeaturesOrBuilder> 
          getTdfFieldBuilder() {
        if (tdfBuilder_ == null) {
          tdfBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeaturesOrBuilder>(
                  tdf_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          tdf_ = null;
        }
        return tdfBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:helloworld.HelloReply)
    }

    // @@protoc_insertion_point(class_scope:helloworld.HelloReply)
    private static final com.edu.signalAlgorithm.proto.HelloProto.HelloReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.edu.signalAlgorithm.proto.HelloProto.HelloReply();
    }

    public static com.edu.signalAlgorithm.proto.HelloProto.HelloReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloReply>
        PARSER = new com.google.protobuf.AbstractParser<HelloReply>() {
      @java.lang.Override
      public HelloReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.edu.signalAlgorithm.proto.HelloProto.HelloReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TimeDomainFeaturesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:helloworld.TimeDomainFeatures)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1_均值（平均幅值）
     * </pre>
     *
     * <code>double mean = 1;</code>
     * @return The mean.
     */
    double getMean();

    /**
     * <pre>
     *2_标准差
     * </pre>
     *
     * <code>double std = 2;</code>
     * @return The std.
     */
    double getStd();

    /**
     * <pre>
     *3_方根幅值
     * </pre>
     *
     * <code>double rootAmplitude = 3;</code>
     * @return The rootAmplitude.
     */
    double getRootAmplitude();

    /**
     * <pre>
     *4_RMS均方根
     * </pre>
     *
     * <code>double rms = 4;</code>
     * @return The rms.
     */
    double getRms();

    /**
     * <pre>
     *5_峰峰值
     * </pre>
     *
     * <code>double peakToPeak = 5;</code>
     * @return The peakToPeak.
     */
    double getPeakToPeak();

    /**
     * <pre>
     *6_偏度 skewness
     * </pre>
     *
     * <code>double skewness = 6;</code>
     * @return The skewness.
     */
    double getSkewness();

    /**
     * <pre>
     *7_峭度 Kurtosis
     * </pre>
     *
     * <code>double kurtosis = 7;</code>
     * @return The kurtosis.
     */
    double getKurtosis();

    /**
     * <pre>
     *8_峰值因子 Crest Factor
     * </pre>
     *
     * <code>double crestFactor = 8;</code>
     * @return The crestFactor.
     */
    double getCrestFactor();

    /**
     * <pre>
     *9_裕度因子  Clearance Factor
     * </pre>
     *
     * <code>double clearanceFactor = 9;</code>
     * @return The clearanceFactor.
     */
    double getClearanceFactor();

    /**
     * <pre>
     *10_波形因子 Shape Factor
     * </pre>
     *
     * <code>double shapeFactor = 10;</code>
     * @return The shapeFactor.
     */
    double getShapeFactor();

    /**
     * <pre>
     *11_脉冲指数 Impulse Factor
     * </pre>
     *
     * <code>double impulseFactor = 11;</code>
     * @return The impulseFactor.
     */
    double getImpulseFactor();
  }
  /**
   * <pre>
   *TimeDomainFeatures时域特征实体对象
   * </pre>
   *
   * Protobuf type {@code helloworld.TimeDomainFeatures}
   */
  public static final class TimeDomainFeatures extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:helloworld.TimeDomainFeatures)
      TimeDomainFeaturesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TimeDomainFeatures.newBuilder() to construct.
    private TimeDomainFeatures(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimeDomainFeatures() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TimeDomainFeatures();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TimeDomainFeatures(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              mean_ = input.readDouble();
              break;
            }
            case 17: {

              std_ = input.readDouble();
              break;
            }
            case 25: {

              rootAmplitude_ = input.readDouble();
              break;
            }
            case 33: {

              rms_ = input.readDouble();
              break;
            }
            case 41: {

              peakToPeak_ = input.readDouble();
              break;
            }
            case 49: {

              skewness_ = input.readDouble();
              break;
            }
            case 57: {

              kurtosis_ = input.readDouble();
              break;
            }
            case 65: {

              crestFactor_ = input.readDouble();
              break;
            }
            case 73: {

              clearanceFactor_ = input.readDouble();
              break;
            }
            case 81: {

              shapeFactor_ = input.readDouble();
              break;
            }
            case 89: {

              impulseFactor_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_TimeDomainFeatures_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_TimeDomainFeatures_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.class, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder.class);
    }

    public static final int MEAN_FIELD_NUMBER = 1;
    private double mean_;
    /**
     * <pre>
     *1_均值（平均幅值）
     * </pre>
     *
     * <code>double mean = 1;</code>
     * @return The mean.
     */
    @java.lang.Override
    public double getMean() {
      return mean_;
    }

    public static final int STD_FIELD_NUMBER = 2;
    private double std_;
    /**
     * <pre>
     *2_标准差
     * </pre>
     *
     * <code>double std = 2;</code>
     * @return The std.
     */
    @java.lang.Override
    public double getStd() {
      return std_;
    }

    public static final int ROOTAMPLITUDE_FIELD_NUMBER = 3;
    private double rootAmplitude_;
    /**
     * <pre>
     *3_方根幅值
     * </pre>
     *
     * <code>double rootAmplitude = 3;</code>
     * @return The rootAmplitude.
     */
    @java.lang.Override
    public double getRootAmplitude() {
      return rootAmplitude_;
    }

    public static final int RMS_FIELD_NUMBER = 4;
    private double rms_;
    /**
     * <pre>
     *4_RMS均方根
     * </pre>
     *
     * <code>double rms = 4;</code>
     * @return The rms.
     */
    @java.lang.Override
    public double getRms() {
      return rms_;
    }

    public static final int PEAKTOPEAK_FIELD_NUMBER = 5;
    private double peakToPeak_;
    /**
     * <pre>
     *5_峰峰值
     * </pre>
     *
     * <code>double peakToPeak = 5;</code>
     * @return The peakToPeak.
     */
    @java.lang.Override
    public double getPeakToPeak() {
      return peakToPeak_;
    }

    public static final int SKEWNESS_FIELD_NUMBER = 6;
    private double skewness_;
    /**
     * <pre>
     *6_偏度 skewness
     * </pre>
     *
     * <code>double skewness = 6;</code>
     * @return The skewness.
     */
    @java.lang.Override
    public double getSkewness() {
      return skewness_;
    }

    public static final int KURTOSIS_FIELD_NUMBER = 7;
    private double kurtosis_;
    /**
     * <pre>
     *7_峭度 Kurtosis
     * </pre>
     *
     * <code>double kurtosis = 7;</code>
     * @return The kurtosis.
     */
    @java.lang.Override
    public double getKurtosis() {
      return kurtosis_;
    }

    public static final int CRESTFACTOR_FIELD_NUMBER = 8;
    private double crestFactor_;
    /**
     * <pre>
     *8_峰值因子 Crest Factor
     * </pre>
     *
     * <code>double crestFactor = 8;</code>
     * @return The crestFactor.
     */
    @java.lang.Override
    public double getCrestFactor() {
      return crestFactor_;
    }

    public static final int CLEARANCEFACTOR_FIELD_NUMBER = 9;
    private double clearanceFactor_;
    /**
     * <pre>
     *9_裕度因子  Clearance Factor
     * </pre>
     *
     * <code>double clearanceFactor = 9;</code>
     * @return The clearanceFactor.
     */
    @java.lang.Override
    public double getClearanceFactor() {
      return clearanceFactor_;
    }

    public static final int SHAPEFACTOR_FIELD_NUMBER = 10;
    private double shapeFactor_;
    /**
     * <pre>
     *10_波形因子 Shape Factor
     * </pre>
     *
     * <code>double shapeFactor = 10;</code>
     * @return The shapeFactor.
     */
    @java.lang.Override
    public double getShapeFactor() {
      return shapeFactor_;
    }

    public static final int IMPULSEFACTOR_FIELD_NUMBER = 11;
    private double impulseFactor_;
    /**
     * <pre>
     *11_脉冲指数 Impulse Factor
     * </pre>
     *
     * <code>double impulseFactor = 11;</code>
     * @return The impulseFactor.
     */
    @java.lang.Override
    public double getImpulseFactor() {
      return impulseFactor_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mean_ != 0D) {
        output.writeDouble(1, mean_);
      }
      if (std_ != 0D) {
        output.writeDouble(2, std_);
      }
      if (rootAmplitude_ != 0D) {
        output.writeDouble(3, rootAmplitude_);
      }
      if (rms_ != 0D) {
        output.writeDouble(4, rms_);
      }
      if (peakToPeak_ != 0D) {
        output.writeDouble(5, peakToPeak_);
      }
      if (skewness_ != 0D) {
        output.writeDouble(6, skewness_);
      }
      if (kurtosis_ != 0D) {
        output.writeDouble(7, kurtosis_);
      }
      if (crestFactor_ != 0D) {
        output.writeDouble(8, crestFactor_);
      }
      if (clearanceFactor_ != 0D) {
        output.writeDouble(9, clearanceFactor_);
      }
      if (shapeFactor_ != 0D) {
        output.writeDouble(10, shapeFactor_);
      }
      if (impulseFactor_ != 0D) {
        output.writeDouble(11, impulseFactor_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mean_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, mean_);
      }
      if (std_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, std_);
      }
      if (rootAmplitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, rootAmplitude_);
      }
      if (rms_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, rms_);
      }
      if (peakToPeak_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, peakToPeak_);
      }
      if (skewness_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, skewness_);
      }
      if (kurtosis_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, kurtosis_);
      }
      if (crestFactor_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, crestFactor_);
      }
      if (clearanceFactor_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, clearanceFactor_);
      }
      if (shapeFactor_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, shapeFactor_);
      }
      if (impulseFactor_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, impulseFactor_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures)) {
        return super.equals(obj);
      }
      com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures other = (com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures) obj;

      if (java.lang.Double.doubleToLongBits(getMean())
          != java.lang.Double.doubleToLongBits(
              other.getMean())) return false;
      if (java.lang.Double.doubleToLongBits(getStd())
          != java.lang.Double.doubleToLongBits(
              other.getStd())) return false;
      if (java.lang.Double.doubleToLongBits(getRootAmplitude())
          != java.lang.Double.doubleToLongBits(
              other.getRootAmplitude())) return false;
      if (java.lang.Double.doubleToLongBits(getRms())
          != java.lang.Double.doubleToLongBits(
              other.getRms())) return false;
      if (java.lang.Double.doubleToLongBits(getPeakToPeak())
          != java.lang.Double.doubleToLongBits(
              other.getPeakToPeak())) return false;
      if (java.lang.Double.doubleToLongBits(getSkewness())
          != java.lang.Double.doubleToLongBits(
              other.getSkewness())) return false;
      if (java.lang.Double.doubleToLongBits(getKurtosis())
          != java.lang.Double.doubleToLongBits(
              other.getKurtosis())) return false;
      if (java.lang.Double.doubleToLongBits(getCrestFactor())
          != java.lang.Double.doubleToLongBits(
              other.getCrestFactor())) return false;
      if (java.lang.Double.doubleToLongBits(getClearanceFactor())
          != java.lang.Double.doubleToLongBits(
              other.getClearanceFactor())) return false;
      if (java.lang.Double.doubleToLongBits(getShapeFactor())
          != java.lang.Double.doubleToLongBits(
              other.getShapeFactor())) return false;
      if (java.lang.Double.doubleToLongBits(getImpulseFactor())
          != java.lang.Double.doubleToLongBits(
              other.getImpulseFactor())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEAN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMean()));
      hash = (37 * hash) + STD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getStd()));
      hash = (37 * hash) + ROOTAMPLITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRootAmplitude()));
      hash = (37 * hash) + RMS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRms()));
      hash = (37 * hash) + PEAKTOPEAK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPeakToPeak()));
      hash = (37 * hash) + SKEWNESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSkewness()));
      hash = (37 * hash) + KURTOSIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getKurtosis()));
      hash = (37 * hash) + CRESTFACTOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCrestFactor()));
      hash = (37 * hash) + CLEARANCEFACTOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getClearanceFactor()));
      hash = (37 * hash) + SHAPEFACTOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getShapeFactor()));
      hash = (37 * hash) + IMPULSEFACTOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getImpulseFactor()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *TimeDomainFeatures时域特征实体对象
     * </pre>
     *
     * Protobuf type {@code helloworld.TimeDomainFeatures}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:helloworld.TimeDomainFeatures)
        com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeaturesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_TimeDomainFeatures_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_TimeDomainFeatures_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.class, com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.Builder.class);
      }

      // Construct using com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mean_ = 0D;

        std_ = 0D;

        rootAmplitude_ = 0D;

        rms_ = 0D;

        peakToPeak_ = 0D;

        skewness_ = 0D;

        kurtosis_ = 0D;

        crestFactor_ = 0D;

        clearanceFactor_ = 0D;

        shapeFactor_ = 0D;

        impulseFactor_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.edu.signalAlgorithm.proto.HelloProto.internal_static_helloworld_TimeDomainFeatures_descriptor;
      }

      @java.lang.Override
      public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures getDefaultInstanceForType() {
        return com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.getDefaultInstance();
      }

      @java.lang.Override
      public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures build() {
        com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures buildPartial() {
        com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures result = new com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures(this);
        result.mean_ = mean_;
        result.std_ = std_;
        result.rootAmplitude_ = rootAmplitude_;
        result.rms_ = rms_;
        result.peakToPeak_ = peakToPeak_;
        result.skewness_ = skewness_;
        result.kurtosis_ = kurtosis_;
        result.crestFactor_ = crestFactor_;
        result.clearanceFactor_ = clearanceFactor_;
        result.shapeFactor_ = shapeFactor_;
        result.impulseFactor_ = impulseFactor_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures) {
          return mergeFrom((com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures other) {
        if (other == com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures.getDefaultInstance()) return this;
        if (other.getMean() != 0D) {
          setMean(other.getMean());
        }
        if (other.getStd() != 0D) {
          setStd(other.getStd());
        }
        if (other.getRootAmplitude() != 0D) {
          setRootAmplitude(other.getRootAmplitude());
        }
        if (other.getRms() != 0D) {
          setRms(other.getRms());
        }
        if (other.getPeakToPeak() != 0D) {
          setPeakToPeak(other.getPeakToPeak());
        }
        if (other.getSkewness() != 0D) {
          setSkewness(other.getSkewness());
        }
        if (other.getKurtosis() != 0D) {
          setKurtosis(other.getKurtosis());
        }
        if (other.getCrestFactor() != 0D) {
          setCrestFactor(other.getCrestFactor());
        }
        if (other.getClearanceFactor() != 0D) {
          setClearanceFactor(other.getClearanceFactor());
        }
        if (other.getShapeFactor() != 0D) {
          setShapeFactor(other.getShapeFactor());
        }
        if (other.getImpulseFactor() != 0D) {
          setImpulseFactor(other.getImpulseFactor());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double mean_ ;
      /**
       * <pre>
       *1_均值（平均幅值）
       * </pre>
       *
       * <code>double mean = 1;</code>
       * @return The mean.
       */
      @java.lang.Override
      public double getMean() {
        return mean_;
      }
      /**
       * <pre>
       *1_均值（平均幅值）
       * </pre>
       *
       * <code>double mean = 1;</code>
       * @param value The mean to set.
       * @return This builder for chaining.
       */
      public Builder setMean(double value) {
        
        mean_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1_均值（平均幅值）
       * </pre>
       *
       * <code>double mean = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMean() {
        
        mean_ = 0D;
        onChanged();
        return this;
      }

      private double std_ ;
      /**
       * <pre>
       *2_标准差
       * </pre>
       *
       * <code>double std = 2;</code>
       * @return The std.
       */
      @java.lang.Override
      public double getStd() {
        return std_;
      }
      /**
       * <pre>
       *2_标准差
       * </pre>
       *
       * <code>double std = 2;</code>
       * @param value The std to set.
       * @return This builder for chaining.
       */
      public Builder setStd(double value) {
        
        std_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *2_标准差
       * </pre>
       *
       * <code>double std = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStd() {
        
        std_ = 0D;
        onChanged();
        return this;
      }

      private double rootAmplitude_ ;
      /**
       * <pre>
       *3_方根幅值
       * </pre>
       *
       * <code>double rootAmplitude = 3;</code>
       * @return The rootAmplitude.
       */
      @java.lang.Override
      public double getRootAmplitude() {
        return rootAmplitude_;
      }
      /**
       * <pre>
       *3_方根幅值
       * </pre>
       *
       * <code>double rootAmplitude = 3;</code>
       * @param value The rootAmplitude to set.
       * @return This builder for chaining.
       */
      public Builder setRootAmplitude(double value) {
        
        rootAmplitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *3_方根幅值
       * </pre>
       *
       * <code>double rootAmplitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRootAmplitude() {
        
        rootAmplitude_ = 0D;
        onChanged();
        return this;
      }

      private double rms_ ;
      /**
       * <pre>
       *4_RMS均方根
       * </pre>
       *
       * <code>double rms = 4;</code>
       * @return The rms.
       */
      @java.lang.Override
      public double getRms() {
        return rms_;
      }
      /**
       * <pre>
       *4_RMS均方根
       * </pre>
       *
       * <code>double rms = 4;</code>
       * @param value The rms to set.
       * @return This builder for chaining.
       */
      public Builder setRms(double value) {
        
        rms_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *4_RMS均方根
       * </pre>
       *
       * <code>double rms = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRms() {
        
        rms_ = 0D;
        onChanged();
        return this;
      }

      private double peakToPeak_ ;
      /**
       * <pre>
       *5_峰峰值
       * </pre>
       *
       * <code>double peakToPeak = 5;</code>
       * @return The peakToPeak.
       */
      @java.lang.Override
      public double getPeakToPeak() {
        return peakToPeak_;
      }
      /**
       * <pre>
       *5_峰峰值
       * </pre>
       *
       * <code>double peakToPeak = 5;</code>
       * @param value The peakToPeak to set.
       * @return This builder for chaining.
       */
      public Builder setPeakToPeak(double value) {
        
        peakToPeak_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *5_峰峰值
       * </pre>
       *
       * <code>double peakToPeak = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeakToPeak() {
        
        peakToPeak_ = 0D;
        onChanged();
        return this;
      }

      private double skewness_ ;
      /**
       * <pre>
       *6_偏度 skewness
       * </pre>
       *
       * <code>double skewness = 6;</code>
       * @return The skewness.
       */
      @java.lang.Override
      public double getSkewness() {
        return skewness_;
      }
      /**
       * <pre>
       *6_偏度 skewness
       * </pre>
       *
       * <code>double skewness = 6;</code>
       * @param value The skewness to set.
       * @return This builder for chaining.
       */
      public Builder setSkewness(double value) {
        
        skewness_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *6_偏度 skewness
       * </pre>
       *
       * <code>double skewness = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkewness() {
        
        skewness_ = 0D;
        onChanged();
        return this;
      }

      private double kurtosis_ ;
      /**
       * <pre>
       *7_峭度 Kurtosis
       * </pre>
       *
       * <code>double kurtosis = 7;</code>
       * @return The kurtosis.
       */
      @java.lang.Override
      public double getKurtosis() {
        return kurtosis_;
      }
      /**
       * <pre>
       *7_峭度 Kurtosis
       * </pre>
       *
       * <code>double kurtosis = 7;</code>
       * @param value The kurtosis to set.
       * @return This builder for chaining.
       */
      public Builder setKurtosis(double value) {
        
        kurtosis_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *7_峭度 Kurtosis
       * </pre>
       *
       * <code>double kurtosis = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearKurtosis() {
        
        kurtosis_ = 0D;
        onChanged();
        return this;
      }

      private double crestFactor_ ;
      /**
       * <pre>
       *8_峰值因子 Crest Factor
       * </pre>
       *
       * <code>double crestFactor = 8;</code>
       * @return The crestFactor.
       */
      @java.lang.Override
      public double getCrestFactor() {
        return crestFactor_;
      }
      /**
       * <pre>
       *8_峰值因子 Crest Factor
       * </pre>
       *
       * <code>double crestFactor = 8;</code>
       * @param value The crestFactor to set.
       * @return This builder for chaining.
       */
      public Builder setCrestFactor(double value) {
        
        crestFactor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *8_峰值因子 Crest Factor
       * </pre>
       *
       * <code>double crestFactor = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCrestFactor() {
        
        crestFactor_ = 0D;
        onChanged();
        return this;
      }

      private double clearanceFactor_ ;
      /**
       * <pre>
       *9_裕度因子  Clearance Factor
       * </pre>
       *
       * <code>double clearanceFactor = 9;</code>
       * @return The clearanceFactor.
       */
      @java.lang.Override
      public double getClearanceFactor() {
        return clearanceFactor_;
      }
      /**
       * <pre>
       *9_裕度因子  Clearance Factor
       * </pre>
       *
       * <code>double clearanceFactor = 9;</code>
       * @param value The clearanceFactor to set.
       * @return This builder for chaining.
       */
      public Builder setClearanceFactor(double value) {
        
        clearanceFactor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *9_裕度因子  Clearance Factor
       * </pre>
       *
       * <code>double clearanceFactor = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearClearanceFactor() {
        
        clearanceFactor_ = 0D;
        onChanged();
        return this;
      }

      private double shapeFactor_ ;
      /**
       * <pre>
       *10_波形因子 Shape Factor
       * </pre>
       *
       * <code>double shapeFactor = 10;</code>
       * @return The shapeFactor.
       */
      @java.lang.Override
      public double getShapeFactor() {
        return shapeFactor_;
      }
      /**
       * <pre>
       *10_波形因子 Shape Factor
       * </pre>
       *
       * <code>double shapeFactor = 10;</code>
       * @param value The shapeFactor to set.
       * @return This builder for chaining.
       */
      public Builder setShapeFactor(double value) {
        
        shapeFactor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *10_波形因子 Shape Factor
       * </pre>
       *
       * <code>double shapeFactor = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearShapeFactor() {
        
        shapeFactor_ = 0D;
        onChanged();
        return this;
      }

      private double impulseFactor_ ;
      /**
       * <pre>
       *11_脉冲指数 Impulse Factor
       * </pre>
       *
       * <code>double impulseFactor = 11;</code>
       * @return The impulseFactor.
       */
      @java.lang.Override
      public double getImpulseFactor() {
        return impulseFactor_;
      }
      /**
       * <pre>
       *11_脉冲指数 Impulse Factor
       * </pre>
       *
       * <code>double impulseFactor = 11;</code>
       * @param value The impulseFactor to set.
       * @return This builder for chaining.
       */
      public Builder setImpulseFactor(double value) {
        
        impulseFactor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *11_脉冲指数 Impulse Factor
       * </pre>
       *
       * <code>double impulseFactor = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearImpulseFactor() {
        
        impulseFactor_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:helloworld.TimeDomainFeatures)
    }

    // @@protoc_insertion_point(class_scope:helloworld.TimeDomainFeatures)
    private static final com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures();
    }

    public static com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimeDomainFeatures>
        PARSER = new com.google.protobuf.AbstractParser<TimeDomainFeatures>() {
      @java.lang.Override
      public TimeDomainFeatures parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TimeDomainFeatures(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimeDomainFeatures> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimeDomainFeatures> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.edu.signalAlgorithm.proto.HelloProto.TimeDomainFeatures getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_TimeDomainFeatures_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_TimeDomainFeatures_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\"\034\n\014HelloR" +
      "equest\022\014\n\004name\030\001 \001(\t\"J\n\nHelloReply\022\017\n\007me" +
      "ssage\030\001 \001(\t\022+\n\003tdf\030\002 \003(\0132\036.helloworld.Ti" +
      "meDomainFeatures\"\345\001\n\022TimeDomainFeatures\022" +
      "\014\n\004mean\030\001 \001(\001\022\013\n\003std\030\002 \001(\001\022\025\n\rrootAmplit" +
      "ude\030\003 \001(\001\022\013\n\003rms\030\004 \001(\001\022\022\n\npeakToPeak\030\005 \001" +
      "(\001\022\020\n\010skewness\030\006 \001(\001\022\020\n\010kurtosis\030\007 \001(\001\022\023" +
      "\n\013crestFactor\030\010 \001(\001\022\027\n\017clearanceFactor\030\t" +
      " \001(\001\022\023\n\013shapeFactor\030\n \001(\001\022\025\n\rimpulseFact" +
      "or\030\013 \001(\0012I\n\007Greeter\022>\n\010SayHello\022\030.hellow" +
      "orld.HelloRequest\032\026.helloworld.HelloRepl" +
      "y\"\000B-\n\035com.edu.signalAlgorithm.protoB\nHe" +
      "lloProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helloworld_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_helloworld_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloReply_descriptor,
        new java.lang.String[] { "Message", "Tdf", });
    internal_static_helloworld_TimeDomainFeatures_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_TimeDomainFeatures_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_TimeDomainFeatures_descriptor,
        new java.lang.String[] { "Mean", "Std", "RootAmplitude", "Rms", "PeakToPeak", "Skewness", "Kurtosis", "CrestFactor", "ClearanceFactor", "ShapeFactor", "ImpulseFactor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
